### ISSUE TITLE
TODO: testing

### ISSUE THREAD

**Issue by krisbitney** [polywrap/kotlin-client#6]
The following features need to be tested:

- [ ] `resolvePackage` option in `tryResolveUri`, along with `loadPackage` client method
- [ ] `SynchronizedCacheResolver` UriResolver implementation (make sure parallel calls are synchronized)
- [ ] URI resolution more generally
- [ ] Client invocations and wrap test harness (see https://github.com/polywrap/kotlin-client/issues/2)
